stages:
  - test
  - build-image
  - post-test

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/SAST-IaC.latest.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

docker-image-build-api:
  stage: build-image
  image: docker.io/library/docker:24-git
  script:
    - cd api
    - docker build -t $CI_REGISTRY_IMAGE/api:latest -t $CI_REGISTRY_IMAGE/api:$(cat VERSION) -f Dockerfile .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker image push --all-tags $CI_REGISTRY_IMAGE/api
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      exists:
        - api/Dockerfile
      changes:
        - api/*.py
        - api/**/*.py
        - api/requirements.txt
        - api/Dockerfile

docker-image-build-bot:
  stage: build-image
  image: docker.io/library/docker:24-git
  script:
    - cd bot
    - docker build -t $CI_REGISTRY_IMAGE/bot:latest -t $CI_REGISTRY_IMAGE/bot:$(cat VERSION) -f Dockerfile .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker image push --all-tags $CI_REGISTRY_IMAGE/bot
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      exists:
        - bot/Dockerfile
      changes:
        - bot/*.py
        - bot/requirements.txt
        - bot/Dockerfile
