# boapdb-sosaeblabotprem-vapronva
version: "3"

services:
  db:
    image: docker.io/library/mongo:5-focal
    restart: unless-stopped
    user: "1047"
    container_name: "database-sosania_ebla_bot_premium-vapronva-mongodb"
    ports:
      - 27122:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_MONGODB_DATABASE}
    volumes:
      - ${DB_PATH_VOLUME}:/data/db
  api:
    image: registry.vapronva.pw/vapronva/sosanie_ebla_bot_premium-tg_bot/api:latest
    restart: unless-stopped
    user: "1047"
    container_name: "api-sosania_ebla_bot_premium-vapronva-main"
    environment:
      TINKOFF_VOICEKIT_APIKEY: ${TINKOFF_VOICEKIT_APIKEY}
      TINKOFF_VOICEKIT_SECRETKEY: ${TINKOFF_VOICEKIT_SECRETKEY}
      TINKOFF_VOICEKIT_ENDPOINTAPI: ${TINKOFF_VOICEKIT_ENDPOINTAPI}
      YANDEX_SPEECHKIT_FOLDERID: ${YANDEX_SPEECHKIT_FOLDERID}
      YANDEX_SPEECHKIT_APITOKEN: ${YANDEX_SPEECHKIT_APITOKEN}
      VK_CLOUDVOICE_ENDPOINTAPI: ${VK_CLOUDVOICE_ENDPOINTAPI}
      VK_CLOUDVOICE_SERVICETOKEN: ${VK_CLOUDVOICE_SERVICETOKEN}
      SBERBANK_SALUTESPEECH_ENDPOINTAPI: ${SBERBANK_SALUTESPEECH_ENDPOINTAPI}
      VPRW_API_KEY: ${VPRW_API_KEY}
      VPRW_API_ENDPOINT: ${VPRW_API_ENDPOINT}
      API_CONTACT_EMAIL: ${API_CONTACT_EMAIL}
      DB_MONGODB_URI: ${DB_MONGODB_URI}
      SENTRY_DSN: ${SENTRY_DSN_API}
      DEPLOYMENT_ENVIRONMENT: ${DEPLOYMENT_ENVIRONMENT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.boapdb-sosaeblabotprem-vapronva-api.rule=Host(`api.sosanie-ebla-bot-premium.vapronva.pw`)"
      - "traefik.http.routers.boapdb-sosaeblabotprem-vapronva-api.entrypoints=web"
      - "traefik.http.services.boapdb-sosaeblabotprem-vapronva-api.loadbalancer.server.port=8000"
    volumes:
      - ${VOICEMESSAGES_PATH_VOLUME}:/usr/src/app/voice_messages_storage
  bot:
    image: registry.vapronva.pw/vapronva/sosanie_ebla_bot_premium-tg_bot/bot:latest
    restart: unless-stopped
    container_name: "worker-sosania_ebla_bot_premium-vapronva-bot"
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      VPRW_API_KEY: ${VPRW_API_KEY}
      VPRW_API_ENDPOINT: ${VPRW_API_ENDPOINT}
      BOT_CONTACT_USERNAME: ${BOT_CONTACT_USERNAME}
      SENTRY_DSN: ${SENTRY_DSN_BOT}
      DEPLOYMENT_ENVIRONMENT: ${DEPLOYMENT_ENVIRONMENT}

networks:
  default:
    driver: bridge
    name: "boapdb-sosaeblabotprem-vapronva-network"
    ipam:
      driver: default
      config:
        - subnet: 172.16.67.0/24
          gateway: 172.16.67.1
