# boapdb-sosaeblabotprem-vapronva
version: "3"

services:
  db:
    image: mongo:5.0-focal
    restart: unless-stopped
    user: "1047"
    container_name: "database-sosania_ebla_bot_premium-vapronva-mongodb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_MONGODB_DATABASE}
    volumes:
      - ${DB_PATH_VOLUME}:/data/db
  api:
    image: registry.vapronva.pw/vapronva/sosanie_ebla_bot_premium-tg_bot/api:latest
    restart: unless-stopped
    user: "1047"
    container_name: "api-sosania_ebla_bot_premium-vapronva-main"
    environment:
      TINKOFF_VOICEKIT_APIKEY: ${TINKOFF_VOICEKIT_APIKEY}
      TINKOFF_VOICEKIT_SECRETKEY: ${TINKOFF_VOICEKIT_SECRETKEY}
      TINKOFF_VOICEKIT_ENDPOINTAPI: ${TINKOFF_VOICEKIT_ENDPOINTAPI}
      YANDEX_SPEECHKIT_FOLDERID: ${YANDEX_SPEECHKIT_FOLDERID}
      YANDEX_SPEECHKIT_APITOKEN: ${YANDEX_SPEECHKIT_APITOKEN}
      VPRW_API_KEY: ${VPRW_API_KEY}
      VPRW_API_SECRET: ${VPRW_API_SECRET}
      VPRW_API_ENDPOINT: ${VPRW_API_ENDPOINT}
      API_CONTACT_EMAIL: ${API_CONTACT_EMAIL}
      DB_MONGODB_URI: ${DB_MONGODB_URI}
      VIRTUAL_PORT: 8000
      VIRTUAL_HOST: ${VPRW_API_ENDPOINT}
    volumes:
      - ${VOICEMESSAGES_PATH_VOLUME}:/usr/src/app/voice_messages_storage
  bot:
    image: registry.vapronva.pw/vapronva/sosanie_ebla_bot_premium-tg_bot/bot:latest
    restart: unless-stopped
    container_name: "worker-sosania_ebla_bot_premium-vapronva-bot"
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      VPRW_API_KEY: ${VPRW_API_KEY}
      VPRW_API_SECRET: ${VPRW_API_SECRET}
      VPRW_API_ENDPOINT: ${VPRW_API_ENDPOINT}
      BOT_CONTACT_USERNAME: ${BOT_CONTACT_USERNAME}

networks:
  default:
    driver: bridge
    name: "boapdb-sosaeblabotprem-vapronva-network"
    ipam:
      driver: default
      config:
        - subnet: 172.16.67.0/24
          gateway: 172.16.67.1
